# docker-compose.yml
version: '3.8'

services:
  fastapi:
    build: .
    image: gbedu/fastapi-app:latest
    container_name: fastapi-app
    networks:
      - app-network
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge